name: go-wx unit tests
on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            go-version: ['1.16', '1.17', '1.18', '1.19', '1.20', '1.21', '1.22']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: make test
